//Copyright (c) 2016 by ETH Zurich, Alexey Geraskin, Mikhail Kruglyakov, and Alexey Kuvshinov
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extreme.Cartesian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extreme.Cartesian.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background layers are not presented.
        /// </summary>
        internal static string SimpleModelLoader_BackgroundLayersAreNotPresented {
            get {
                return ResourceManager.GetString("SimpleModelLoader_BackgroundLayersAreNotPresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background layers have wring indeving.
        /// </summary>
        internal static string SimpleModelLoader_BackgroundLayersWrongIndecies {
            get {
                return ResourceManager.GetString("SimpleModelLoader_BackgroundLayersWrongIndecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tau model section is not presented.
        /// </summary>
        internal static string SimpleModelLoader_TauModelIsNotPresented {
            get {
                return ResourceManager.GetString("SimpleModelLoader_TauModelIsNotPresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version.
        /// </summary>
        internal static string SimpleModelLoader_UnknownVersion {
            get {
                return ResourceManager.GetString("SimpleModelLoader_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong xml file.
        /// </summary>
        internal static string SimpleModelLoader_WrongXmlFormat {
            get {
                return ResourceManager.GetString("SimpleModelLoader_WrongXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load project due to error in file name.
        /// </summary>
        internal static string SimpleProjectLoader_WrongFileName {
            get {
                return ResourceManager.GetString("SimpleProjectLoader_WrongFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong xml file.
        /// </summary>
        internal static string SimpleProjectLoader_WrongXmlFormat {
            get {
                return ResourceManager.GetString("SimpleProjectLoader_WrongXmlFormat", resourceCulture);
            }
        }
    }
}
