//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extreme.Cartesian {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HankelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HankelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extreme.Cartesian.HankelResources", typeof(HankelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Hankel&gt;
        ///  &lt;Coefficients name=&quot;ndec15&quot; ndec=&quot;15&quot; omegah=&quot;0.5&quot; epsh=&quot;1E-12&quot; ncoef=&quot;431&quot;&gt;
        ///    &lt;line x=&quot;-46.1&quot; h0=&quot;1.535056728662686E-21&quot; h1=&quot;7.6707510734076685E-42&quot; /&gt;
        ///    &lt;line x=&quot;-45.9&quot; h0=&quot;1.789744746575846E-21&quot; h1=&quot;1.043965144902323E-41&quot; /&gt;
        ///    &lt;line x=&quot;-45.7&quot; h0=&quot;2.0866891744687081E-21&quot; h1=&quot;1.417427522220314E-41&quot; /&gt;
        ///    &lt;line x=&quot;-45.6&quot; h0=&quot;2.4329009592991479E-21&quot; h1=&quot;1.9291072922610729E-41&quot; /&gt;
        ///    &lt;line x=&quot;-45.4&quot; h0=&quot;2.8365542650910791E-21&quot; h1=&quot;2.619170554816 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hankelcoeff {
            get {
                return ResourceManager.GetString("hankelcoeff", resourceCulture);
            }
        }
    }
}
